version: '3'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-vixen-bot
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=production
